routes/web.php
<?php

use App\Http\Controllers\Admin\Mahasiswa;
use App\Http\Controllers\Admin\Pengaturan;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//   echo "Hello world";
// });
Route::get('/', function () {
  return redirect()->route('mahasiswa.read');
});


// ROUTE AUTH
Route::get('/login', [LoginController::class, 'getLogin'])->middleware('guest')->name('login');
Route::post('/login', [LoginController::class, 'postLogin']);
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');


// ROUTE PENGATURAN
Route::prefix('pengaturan')->middleware('auth')->name('pengaturan.')->group(function () {
  Route::get('/', function () {
    return redirect()->route('pengaturan.deskripsi-sistem');
  });

  Route::prefix('deskripsi-sistem')->group(function () {
    Route::get('/', [Pengaturan::class, 'get_deskripsi_sistem'])->name('deskripsi-sistem');
    Route::post('/', [Pengaturan::class, 'post_deskripsi_sistem']);
  });
});

// ROUTE MAHASISWA
Route::prefix('mahasiswa')->middleware('auth')->name('mahasiswa.')->group(function () {
  Route::get('/', [Mahasiswa::class, 'read'])->name('read');

  Route::get('create', [Mahasiswa::class, 'create'])->name('create');
  Route::post('create', [Mahasiswa::class, 'create_post']);

  Route::get('update/{id}', [Mahasiswa::class, 'update'])->where(['id' => '[0-9]+'])->name('update');
  Route::post('update/{id}', [Mahasiswa::class, 'update_post'])->where(['id' => '[0-9]+']);

  Route::post('delete', [Mahasiswa::class, 'delete_post'])->name('delete');

  Route::get('datatable', [Mahasiswa::class, 'datatable'])->name('datatable');

  Route::get('export-all/{tipe}', [Mahasiswa::class, 'export_all'])->name('export-all');
});

app/Http/Controllers/Admin/Mahasiswa.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\ExportExcel;
use App\Exports\ExportExcelMultipleSheets;
use App\Exports\MhsExport;
use App\Http\Controllers\Controller;
use App\Models\TbMhs;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;

class Mahasiswa extends Controller
{
  private $route_root = 'mahasiswa.';

  public function prepare_index($data = [])
  {
    return array_merge($data, [
      'sidebar' => 'mahasiswa'
    ]);
  }

  // READ
  public function read()
  {
    return view('pages.mahasiswa.read', $this->prepare_index());
  }

  // CREATE
  public function create()
  {
    return view('pages.mahasiswa.create', $this->prepare_index());
  }
  public function create_post(Request $request)
  {
    $validated_data = $request->validate([
      'nim'  => ['required', 'numeric', 'digits_between:1,20', 'unique:tb_mhs,nim'],
      'nama' => ['required', 'string', 'max:255'],
      'jk'   => ['required', 'string', 'max:1', 'in:L,P'],
    ]);

    try {
      TbMhs::create([
        'nim'  => $request['nim'],
        'nama' => $request['nama'],
        'jk'   => $request['jk'],
      ]);

      return redirect()->route($this->route_root . 'read')->with('toastr_succ', 'Simpan data sukses');
    } catch (\Throwable $th) {
      return back()->with('toastr_erro', 'Terjadi kesalahan saat menyimpan data');
    }
  }

  // UPDATE
  public function update($id)
  {
    $data = [
      'data_edit' => TbMhs::find($id)
    ];

    if (!$data['data_edit']) {
      return back();
    }

    return view('pages.mahasiswa.update', $this->prepare_index($data));
  }
  public function update_post(Request $request)
  {
    $validated_data = $request->validate([
      'nim'  => ['required', 'numeric', 'digits_between:1,20', 'unique:tb_mhs,nim,' . $request['id']],
      'nama' => ['required', 'string', 'max:255'],
      'jk'   => ['required', 'string', 'max:1', 'in:L,P'],
    ]);

    try {
      $data_edit = TbMhs::find($request['id']);
      if (!$data_edit) {
        return back()->with('toastr_erro', 'Data tidak ditemukan');
      }

      $data_edit['nim']  = $request['nim'];
      $data_edit['nama'] = $request['nama'];
      $data_edit['jk']   = $request['jk'];
      $data_edit->save();

      return redirect()->route($this->route_root . 'read')->with('toastr_succ', 'Update data sukses');
    } catch (\Throwable $th) {
      return back()->with('toastr_erro', 'Terjadi kesalahan saat memperbaharui data');
    }
  }

  // DELETE
  public function delete_post(Request $request)
  {
    try {
      if (TbMhs::destroy($request['id'])) {
        return redirect()->route($this->route_root . 'read')->with('toastr_succ', 'Hapus data sukses');
      }

      return back()->with('toastr_erro', 'Data masih digunakan pada fungsional lainnya');
    } catch (\Throwable $th) {
      return back()->with('toastr_erro', 'Terjadi kesalahan saat menghapus data');
    }
  }

  // DATATABLE
  public function datatable()
  {
    $data = TbMhs::select(
      'tb_mhs.id',
      'tb_mhs.nim',
      'tb_mhs.nama',
      'tb_mhs.jk',
      'tb_mhs.created_at',
      'tb_mhs.updated_at',
    );

    return DataTables::of($data)
      ->addColumn('created_at', function ($data) {
        return date("d/m/Y H:i:s", strtotime($data->created_at));
      })
      ->addColumn('updated_at', function ($data) {
        return date("d/m/Y H:i:s", strtotime($data->updated_at));
      })
      ->addColumn('jk', function ($data) {
        return $data->jk == "L" ? "Laki - laki" : ($data->jk == "P" ? "Perempuan" : "Other");
      })
      ->addColumn('action', function ($data) {
        return '
          <a class="btn btn-sm btn-primary btn-icon-split" href="' . route('mahasiswa.update', ['id' => $data->id]) . '">
            <span class="icon text-white-50">
              <i class="fas fa-pencil-alt"></i>
            </span>
            <span class="text">Edit</span>
          </a>

          <button class="btn btn-sm btn-danger btn-icon-split" onclick="toggleModalDelete(\'data-table-del-info-' . $data->id . '\', \'' . $data->id . '\')">
            <span class="icon text-white-50">
                <i class="fas fa-trash"></i>
            </span>
            <span class="text">Hapus</span>
          </button>
          <span id="data-table-del-info-' . $data->id . '" class="d-none">' . $data->nim . ' - ' . $data->nama . '</span>
        ';
      })
      ->addIndexColumn()
      ->escapeColumns([])
      ->make(true);
  }

  public function export_all($tipe)
  {
    if ($tipe == "excel") {
      // return Excel::download(new MhsExport, 'Data Mahasiswa.xlsx', \Maatwebsite\Excel\Excel::XLSX);

      // return Excel::download(new ExportExcel(
      //   [
      //     'view_path'  => 'exports.mhs',
      //     'data_excel' => TbMhs::all(),
      //     'title'      => 'LEMBAR1',
      //   ]
      // ), 'Data Mahasiswa.xlsx', \Maatwebsite\Excel\Excel::XLSX);

      return Excel::download(new ExportExcelMultipleSheets(
        [
          [
            'view_path'  => 'exports.mhs',
            'data_excel' => TbMhs::all(),
            'title'      => 'LEMBAR1',
          ],
          [
            'view_path'  => 'exports.mhs',
            'data_excel' => TbMhs::all(),
            'title'      => 'LEMBAR2',
          ],
        ]
      ), 'Data Mahasiswa.xlsx', \Maatwebsite\Excel\Excel::XLSX);
    }

    if ($tipe == "pdf") {
      // return Excel::download(new MhsExport, 'Data Mahasiswa.pdf', \Maatwebsite\Excel\Excel::MPDF);

      return Excel::download(new ExportExcel(
        [
          'view_path'  => 'exports.mhs',
          'data_excel' => TbMhs::all(),
          'title'      => 'LEMBAR1',
        ]
      ), 'Data Mahasiswa.pdf', \Maatwebsite\Excel\Excel::MPDF);
    }

    abort(404);
  }
}

resources/views/pages/mahasiswa/create.blade.php
@extends('template.layout')

@section('title')
Tambah Data Mahasiswa
@endsection

@section('content')
<div class="row">
  <div class="col-12">
    <form method="POST" action="{{route('mahasiswa.create')}}" enctype="multipart/form-data">
      @csrf
      <div class="card mb-4">
        <div class="card-header">
          Tambah Data Mahasiswa
        </div>
        <div class="card-body">
          <div class="form-group">
            <label for="nim">NIM</label>
            <input id="nim" name="nim" type="text" class="form-control @if($errors->has('nim')) is-invalid @endif" @if(!empty($errors->all())) value="{{old('nim')}}" @else @endif>
            <div id="nim-error" class="invalid-feedback">
              {{$errors->first('nim')}}
            </div>
          </div>

          <div class="form-group">
            <label for="nama">Nama</label>
            <input id="nama" name="nama" type="text" class="form-control @if($errors->has('nama')) is-invalid @endif" @if(!empty($errors->all())) value="{{old('nama')}}" @else @endif>
            <div id="nama-error" class="invalid-feedback">
              {{$errors->first('nama')}}
            </div>
          </div>


          <div class="form-group">
            <label for="nama">Jenis Kelamin</label>

            <div class="form-check">
              <input type="radio" name="jk" value="L" class="form-check-input" id="jk-l">
              <label class="form-check-label" for="jk-l">Laki - laki</label>

              <input type="radio" name="jk" value="P" class="form-check-input" id="jk-p" style="margin-left: 1.25rem">
              <label class="form-check-label" for="jk-p" style="margin-left: 2.5rem">Perempuan</label>
            </div>
            <small id="nama-error" class="text-danger">
              {{$errors->first('jk')}}
            </small>
          </div>
        </div>
        <div class="card-footer text-muted">
          <button type="submit" class="btn btn-primary float-right">SIMPAN</button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('css')
@endsection

@section('js')
@endsection

resources/views/pages/mahasiswa/read.blade.php
@extends('template.layout')

@section('title')
Data Mahasiswa
@endsection

@section('content')
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-header">
        Data Mahasiswa

        <a href="{{route('mahasiswa.create')}}" class="btn btn-sm btn-primary float-right">Tambah</a>
        <a href="{{route('mahasiswa.export-all', ['tipe' => "excel"])}}" class="btn btn-sm btn-success float-right mr-2">Export Excel</a>
        <a href="{{route('mahasiswa.export-all', ['tipe' => "pdf"])}}" class="btn btn-sm btn-danger float-right mr-2">Export PDF</a>
      </div>
      <div class="card-body">

        <div class="table-responsive">
          <table class="table table-bordered" id="data-table" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>#</th>
                <th>NIM</th>
                <th>Nama</th>
                <th>Jenis Kelamin</th>
                <th>Terakhir Diperbaharui</th>
                <th>Action</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>#</th>
                <th>NIM</th>
                <th>Nama</th>
                <th>Jenis Kelamin</th>
                <th>Terakhir Diperbaharui</th>
                <th>Action</th>
              </tr>
            </tfoot>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal Delete -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDeleteLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalDeleteLabel">Konfirmasi Hapus Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Hapus data <strong><i><span id="msg-delete"></span></i></strong> ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Keluar</button>
        <form action="{{route('mahasiswa.delete')}}" method="post">
          @csrf
          <input type="hidden" name="id" value="">
          <button type="submit" class="btn btn-danger">Hapus Data</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('css')
<link href="{{url('/public')}}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('js')
<script src="{{url('/public')}}/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="{{url('/public')}}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<script>
  $(document).ready(function() {
    $('#data-table').dataTable({
      processing: true,
      serverSide: true,
      ajax: "{{route('mahasiswa.datatable')}}",
      columns: [{
          data: 'DT_RowIndex',
          name: 'DT_RowIndex',
          render: null,
          orderable: false,
          searchable: false,
          exportable: false,
          printable: true,
          footer: '',
        },
        {
          data: 'nim',
          name: 'nim'
        },
        {
          data: 'nama',
          name: 'nama'
        },
        {
          data: 'jk',
          name: 'jk'
        },
        {
          data: 'updated_at',
          name: 'updated_at'
        },
        {
          data: 'action',
          name: 'action'
        },
      ]
    });
  });
</script>

{{-- MODAL DELETE --}}
<script>
  function toggleModalDelete(id_msg, id) {
    $("#msg-delete").html($("#" + id_msg).text())
    $("input[name='id']").val(id)
    $('#modalDelete').modal('toggle')
  }
</script>
@endsection

resources/views/pages/mahasiswa/update.blade.php
@extends('template.layout')

@section('title')
Edit Data Mahasiswa
@endsection

@section('content')
<div class="row">
  <div class="col-12">
    <form method="POST" action="{{route('mahasiswa.update', ['id' => $data_edit['id']])}}" enctype="multipart/form-data">
      @csrf
      <input type="hidden" name="id" value="{{$data_edit['id']}}">
      <div class="card mb-4">
        <div class="card-header">
          Edit Data Mahasiswa
        </div>
        <div class="card-body">
          <div class="form-group">
            <label for="nim">NIM</label>
            <input id="nim" name="nim" type="text" class="form-control @if($errors->has('nim')) is-invalid @endif" @if(!empty($errors->all())) value="{{old('nim')}}" @else value="{{$data_edit['nim']}}" @endif>
            <div id="nim-error" class="invalid-feedback">
              {{$errors->first('nim')}}
            </div>
          </div>

          <div class="form-group">
            <label for="nama">Nama</label>
            <input id="nama" name="nama" type="text" class="form-control @if($errors->has('nama')) is-invalid @endif" @if(!empty($errors->all())) value="{{old('nama')}}" @else value="{{$data_edit['nama']}}" @endif>
            <div id="nama-error" class="invalid-feedback">
              {{$errors->first('nama')}}
            </div>
          </div>


          <div class="form-group">
            <label for="nama">Jenis Kelamin</label>

            <div class="form-check">
              <input type="radio" name="jk" value="L" {{$data_edit['jk'] == "L" ? "checked" : ""}} class="form-check-input" id="jk-l">
              <label class="form-check-label" for="jk-l">Laki - laki</label>

              <input type="radio" name="jk" value="P" {{$data_edit['jk'] == "P" ? "checked" : ""}} class="form-check-input" id="jk-p" style="margin-left: 1.25rem">
              <label class="form-check-label" for="jk-p" style="margin-left: 2.5rem">Perempuan</label>
            </div>
            <small id="nama-error" class="text-danger">
              {{$errors->first('jk')}}
            </small>
          </div>
        </div>
        <div class="card-footer text-muted">
          <button type="submit" class="btn btn-primary float-right">SIMPAN PERUBAHAN</button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('css')
@endsection

@section('js')
@endsection